import math
corner = float(input("Podaj wartość w stopniach Celscjusza:"))
print("Sinus:")
print(math.sin(corner))
print("Cosinus")
print(math.cos(corner))
print("Tangens:")
print(math.tan(corner))
print("Cotanges")
ctg = 1/math.tan(corner)
print(ctg)